// Copyright (C) 2025 Zac Sweers
// Copyright (C) 2025 Randall Norviel
// SPDX-License-Identifier: Apache-2.0
package org.noblecow.hrservice.viewmodel

import android.app.Application
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider.AndroidViewModelFactory.Companion.APPLICATION_KEY
import androidx.lifecycle.createSavedStateHandle
import androidx.lifecycle.viewmodel.CreationExtras
import dev.zacsweers.metro.GraphExtension
import dev.zacsweers.metro.Multibinds
import dev.zacsweers.metro.Provider
import dev.zacsweers.metro.Provides
import kotlin.reflect.KClass
import org.noblecow.hrservice.di.ViewModelScope

/**
 * Metro DI graph extension for ViewModel dependency injection.
 *
 * This graph provides:
 * - A map of ViewModel providers for factory-based ViewModel creation
 * - Access to Android Application context via CreationExtras
 * - SavedStateHandle for ViewModels that need state preservation
 *
 * ViewModels are registered in this graph using `@ContributesIntoMap` with `@ViewModelKey`.
 *
 * Example usage:
 * ```kotlin
 * @ContributesIntoMap(ViewModelScope::class)
 * @ViewModelKey(MainViewModel::class)
 * @Inject
 * fun provideMainViewModel(...): ViewModel = MainViewModel(...)
 * ```
 *
 * @see MetroViewModelFactory for usage of this graph
 */
@GraphExtension(ViewModelScope::class)
interface ViewModelGraph {
    /**
     * Map of ViewModel class types to their corresponding providers.
     * Populated at compile-time by Metro via `@ContributesIntoMap` annotations.
     */
    @Multibinds
    val viewModelProviders: Map<KClass<out ViewModel>, Provider<ViewModel>>

    /**
     * Provides the Android Application instance from CreationExtras.
     *
     * @param creationExtras The extras provided when creating a ViewModel
     * @return The Application instance
     * @throws IllegalArgumentException if APPLICATION_KEY is not present in CreationExtras
     */
    @Provides
    fun provideApplication(creationExtras: CreationExtras): Application =
        requireNotNull(creationExtras[APPLICATION_KEY]) {
            "Application not found in CreationExtras. This should never happen when " +
                "creating ViewModels via ViewModelProvider."
        }

    /**
     * Provides a SavedStateHandle for ViewModels that need state preservation.
     *
     * @param creationExtras The extras provided when creating a ViewModel
     * @return A SavedStateHandle for accessing saved state
     */
    @Provides
    fun provideSavedStateHandle(creationExtras: CreationExtras): SavedStateHandle =
        creationExtras.createSavedStateHandle()

    /**
     * Factory for creating ViewModelGraph instances with provided CreationExtras.
     *
     * This factory is generated by Metro and is used by [MetroViewModelFactory]
     * to create ViewModel instances with proper dependency injection.
     */
    @GraphExtension.Factory
    fun interface Factory {
        /**
         * Creates a ViewModelGraph with the given CreationExtras.
         *
         * @param creationExtras The extras containing Application and SavedStateHandle
         * @return A configured ViewModelGraph instance
         */
        fun createViewModelGraph(@Provides creationExtras: CreationExtras): ViewModelGraph
    }
}
