#!/bin/sh

# If you use the detekt and/or ktlint IDE plugins, you can run this from a git hook;
# e.g. .git/hooks/post-checkout

COMPOSE_RULES_VER="$(grep -E 'compose-rules = "[0-9]' gradle/libs.versions.toml | cut -f 2 -d \")"
OUTPUT_DIR="${HOME}/lint-rules"
JARS="detekt ktlint"

if [[ -z $COMPOSE_RULES_VER ]]; then
    echo "Unable to find Compose Rules version in libs.versions.toml"
    exit 1
fi

mkdir -p ${OUTPUT_DIR}

for JAR in ${JARS}; do
    echo $COMPOSE_RULES_VER
    if [ ! -f ${OUTPUT_DIR}/${JAR}-compose-${COMPOSE_RULES_VER}-all.jar ]; then
	echo "Fetching ${JAR}-compose-${COMPOSE_RULES}-all.jar ..."
	curl -L -OJ --output-dir ${OUTPUT_DIR} \
	     https://github.com/mrmans0n/compose-rules/releases/download/v${COMPOSE_RULES_VER}/${JAR}-compose-${COMPOSE_RULES_VER}-all.jar
    fi
done


