#!/bin/bash

RERUN_TASKS=""

while getopts "r" opt; do
    case "$opt" in
	r) RERUN_TASKS="--rerun-tasks"
	   ;;
    esac
done

./gradlew ${RERUN_TASKS} detektAndroidDebug detektIosArm64Main ktlintCheck testDebugUnitTest connectedAndroidTest
